feign:
  clients:
    github:
      base-url: https://api.github.com
      request-headers:
        K-AppCode: java
        K-AppKey: helloworld
        K-SignVer: 2
      loglovel: FULL
      contract-class: JAXRSContract.class
      client-class: ApacheHttpClient.class
      encoderClass: JacksonEncoder.class
      decoderClass: JacksonDecoder.class
    huobi:
      base-url: https://api.huobi.pro/market
      loglovel: FULL