feign:
  clients:
    github:
      base-url: https://api.github.com
      request-headers:
        K-AppCode: java
        K-AppKey: helloworld
        K-SignVer: 2
    huobi:
      base-url: https://api.huobi.pro/market
      loglovel: FULL